# Generated by Django 4.2.23 on 2025-07-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_reserva_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reserva',
            new_name='Paquete',
        ),
    ]
