# Generated by Django 4.2.23 on 2025-07-26 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_reserva_paquete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paquete', models.CharField(max_length=100)),
                ('fecha_tour', models.DateField()),
                ('cantidad_personas', models.IntegerField()),
                ('extra_guia_bilingue', models.BooleanField(default=False)),
                ('extra_souvenir', models.BooleanField(default=False)),
                ('extra_seguro_viaje', models.BooleanField(default=False)),
                ('total_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.registrocliente')),
            ],
        ),
    ]
